-- AlterTable
ALTER TABLE `systemsettings` ADD COLUMN `darkBackgroundColor` VARCHAR(191) NOT NULL DEFAULT '#0F172A',
    ADD COLUMN `darkBorderColor` VARCHAR(191) NOT NULL DEFAULT '#334155',
    ADD COLUMN `darkSurfaceColor` VARCHAR(191) NOT NULL DEFAULT '#1E293B',
    ADD COLUMN `lightBackgroundColor` VARCHAR(191) NOT NULL DEFAULT '#F1F5F9',
    ADD COLUMN `lightBorderColor` VARCHAR(191) NOT NULL DEFAULT '#E2E8F0',
    ADD COLUMN `lightSurfaceColor` VARCHAR(191) NOT NULL DEFAULT '#FFFFFF';
